version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      # interval: 1m30s
      # timeout: 30s
      # retries: 5
      # start_period: 30s
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    # command: bash -c "apt-get update && apt-get install -y tzdata && ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata && python manage.py runserver 0.0.0.0:8000"
    # command to run migrations and populate database with 3 basic tiers and superuser
    command: bash -c "apt-get update && apt-get install -y tzdata && ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata && python manage.py migrate && python manage.py makemigrations && python manage.py migrate && python manage.py pop_tiers || true && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/hex_ocean
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy



      